
export const GET_JOB_REQUEST = "GET_JOB_REQUEST"
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS"
export const GET_JOB_FAILURE = "GET_JOB_FAILURE"
export const ADD_JOB_FILTER = "ADD_JOB_FILTER"
export const CLEAR_JOB_FILTER = "CLEAR_JOB_FILTER"

export const GET_FORUM_REQUEST = "GET_FORUM_REQUEST"
export const GET_FORUM_SUCCESS = "GET_FORUM_SUCCESS"
export const GET_FORUM_FAILURE = "GET_FORUM_FAILURE"
export const ADD_FORUM_FILTER = "ADD_FORUM_FILTER"
export const CLEAR_FORUM_FILTER = "CLEAR_FORUM_FILTER"

export const GET_THREADS_REQUEST = "GET_THREADS_REQUEST"
export const GET_THREADS_SUCCESS = "GET_THREADS_SUCCESS"
export const GET_THREADS_FAILURE = "GET_THREADS_FAILURE"